//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] E1903693365_541449020000700550_190605 {
            get {
                object obj = ResourceManager.GetObject("E1903693365_541449020000700550_190605", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] N1900420442_541449060017014325_190605 {
            get {
                object obj = ResourceManager.GetObject("N1900420442_541449060017014325_190605", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SFM402173INV359097Annexe1 {
            get {
                object obj = ResourceManager.GetObject("SFM402173INV359097Annexe1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SFM402173INV359097Annexe2 {
            get {
                object obj = ResourceManager.GetObject("SFM402173INV359097Annexe2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à %PDF-1.4
        ///%ª«¬­
        ///4 0 obj
        ///&lt;&lt;
        ////Creator (Apache FOP Version 1.0)
        ////Producer (Apache FOP Version 1.0)
        ////CreationDate (D:20190529152105Z)
        ///&gt;&gt;
        ///endobj
        ///5 0 obj
        ///&lt;&lt;
        ///  /N 3
        ///  /Length 11 0 R
        ///  /Filter /FlateDecode
        ///&gt;&gt;
        ///stream
        ///xœ–wTSÙ‡Ï½7½P’Š”ÐkhRH        ///½H‘.*1	JÀ&quot;6DTpDQ‘¦2(à€£C‘±&quot;Š…Q±ëDÔqp–Id­ß¼yïÍ›ß÷~kŸ½ÏÝgï}ÖºüƒÂLX	€¡XáçÅˆ‹g`ðlàp³³BøF™|ØŒl™ø½º ùû*Ó?ŒÁÿŸ”¹Y&quot;1P˜ŒçòøÙ\É8=Wœ%·OÉ˜¶4MÎ0JÎ&quot;Y‚2V“sò,[|ö™e9ó2„&lt;ËsÎâeðäÜ&apos;ã9¾Œ‘`çø¹2¾&amp;cƒtI†@Æoä±|N6(’Ü.æsSdl-c’(2‚-ãyàHÉ_ðÒ/XÌÏËÅÎÌZ.$§ˆ&amp;\S†“‹á [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string WrongExtensionTxt {
            get {
                return ResourceManager.GetString("WrongExtensionTxt", resourceCulture);
            }
        }
    }
}
